name: Hello
on: [push, pull_request]
jobs:
  hello:
    runs-on: ubuntu-latest
      steps:
      - run: |
          echo "Hello, world!"
          tree -a .
      - uses: actions/checkout@v4
        with:
          ref: main
