name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: choice
        default: Hello
        options:
          - Hello
          - Hi
          - Hey
        required: true
        description: a cheeful word
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
      - run: date
